#!/usr/bin/env node
/**
 * Test exec() builtin and import sol_N syntax
 *
 * exec(code) - Execute Python source code string in current scope
 * import sol_N - Import Python module from Solana account by index
 *
 * These provide two ways to run dynamic code:
 * 1. exec() for inline code strings
 * 2. import sol_N for code stored in accounts
 */

const {
    Connection,
    Keypair,
    PublicKey,
    Transaction,
    TransactionInstruction,
    sendAndConfirmTransaction,
    ComputeBudgetProgram,
    SystemProgram,
} = require('@solana/web3.js');
const fs = require('fs');
const path = require('path');

const RPC_URL = 'http://localhost:8899';
const PIKA_KEYPAIR_PATH = path.join(__dirname, '..', 'pika-keypair.json');

const MODE_EXECUTE_SCRIPT = 0x00;
const MODE_GENERATE_BYTECODE = 0x01;
const MODE_WRITE_ACCOUNT = 0x03;

const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const CYAN = '\x1b[36m';
const RESET = '\x1b[0m';

let testsPassed = 0;
let testsFailed = 0;

function loadProgramId(keypairPath) {
    const keypairData = JSON.parse(fs.readFileSync(keypairPath, 'utf8'));
    const keypair = Keypair.fromSecretKey(new Uint8Array(keypairData));
    return keypair.publicKey;
}

function loadPayer() {
    const payerKeypairPath = process.env.HOME + '/.config/solana/id.json';
    const payerKeypair = JSON.parse(fs.readFileSync(payerKeypairPath, 'utf8'));
    return Keypair.fromSecretKey(new Uint8Array(payerKeypair));
}

async function createTestAccount(connection, payer, programId, dataSize) {
    const testAccount = Keypair.generate();
    const rentExempt = await connection.getMinimumBalanceForRentExemption(dataSize);

    const createTx = new Transaction().add(
        SystemProgram.createAccount({
            fromPubkey: payer.publicKey,
            newAccountPubkey: testAccount.publicKey,
            lamports: rentExempt,
            space: dataSize,
            programId: programId,
        })
    );

    await sendAndConfirmTransaction(connection, createTx, [payer, testAccount]);
    return testAccount;
}

async function executePython(connection, programId, payer, pythonCode, accounts) {
    const modeBuffer = Buffer.alloc(1);
    modeBuffer.writeUInt8(MODE_EXECUTE_SCRIPT, 0);
    const data = Buffer.concat([modeBuffer, Buffer.from(pythonCode, 'utf8')]);

    const keys = accounts.map(acc => ({
        pubkey: acc.pubkey,
        isSigner: false,
        isWritable: acc.writable,
    }));

    const instruction = new TransactionInstruction({
        keys,
        programId,
        data,
    });

    const transaction = new Transaction();
    transaction.add(
        ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
        ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        instruction
    );

    transaction.feePayer = payer.publicKey;
    transaction.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;

    const simResult = await connection.simulateTransaction(transaction);

    // Extract output and CU from logs
    const output = simResult.value.logs?.filter(log =>
        log.startsWith('Program log:') &&
        !log.includes('Generated bytecode') &&
        !log.includes('VFS initialized')
    ).map(log => log.replace('Program log: ', '')).join('\n') || '';

    const cuLog = simResult.value.logs?.find(log => log.includes('consumed'));
    const cuMatch = cuLog?.match(/consumed (\d+) of/);
    const computeUnits = cuMatch ? parseInt(cuMatch[1]) : 0;

    if (simResult.value.err) {
        return { success: false, output, computeUnits, logs: simResult.value.logs, error: simResult.value.err };
    }

    // Send transaction to persist writes
    try {
        await sendAndConfirmTransaction(connection, transaction, [payer], {
            commitment: 'confirmed',
            skipPreflight: true,
        });
    } catch (e) { }

    return { success: true, output, computeUnits, logs: simResult.value.logs };
}

async function generateBytecode(connection, programId, payer, pythonCode) {
    const modeBuffer = Buffer.alloc(1);
    modeBuffer.writeUInt8(MODE_GENERATE_BYTECODE, 0);
    const data = Buffer.concat([modeBuffer, Buffer.from(pythonCode, 'utf8')]);

    const instruction = new TransactionInstruction({
        keys: [],
        programId,
        data,
    });

    const transaction = new Transaction();
    transaction.add(
        ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
        ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        instruction
    );

    transaction.feePayer = payer.publicKey;
    transaction.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;

    const simResult = await connection.simulateTransaction(transaction);

    const cuLog = simResult.value.logs?.find(log => log.includes('consumed'));
    const cuMatch = cuLog?.match(/consumed (\d+) of/);
    const computeUnits = cuMatch ? parseInt(cuMatch[1]) : 0;

    if (simResult.value.err) {
        return { success: false, bytecode: Buffer.alloc(0), computeUnits, logs: simResult.value.logs };
    }

    // Extract bytecode from return data
    const returnData = simResult.value.returnData;
    if (!returnData || !returnData.data) {
        // Try to extract from logs (fallback)
        const bcLog = simResult.value.logs?.find(log => log.includes('Generated bytecode'));
        if (bcLog) {
            const hexMatch = bcLog.match(/0x([0-9a-f]+)/i);
            if (hexMatch) {
                const bytecode = Buffer.from(hexMatch[1], 'hex');
                return { success: true, bytecode, computeUnits };
            }
        }
        return { success: false, bytecode: Buffer.alloc(0), computeUnits, logs: simResult.value.logs };
    }

    const bytecode = Buffer.from(returnData.data[0], 'base64');
    return { success: true, bytecode, computeUnits };
}

async function writeAccountDirect(connection, programId, payer, account, data) {
    const modeBuffer = Buffer.alloc(1);
    modeBuffer.writeUInt8(MODE_WRITE_ACCOUNT, 0);
    const instructionData = Buffer.concat([modeBuffer, data]);

    const instruction = new TransactionInstruction({
        keys: [{
            pubkey: account.publicKey,
            isSigner: false,
            isWritable: true,
        }],
        programId,
        data: instructionData,
    });

    const transaction = new Transaction();
    transaction.add(
        ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        instruction
    );
    transaction.feePayer = payer.publicKey;
    transaction.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;

    const simResult = await connection.simulateTransaction(transaction);

    if (simResult.value.err) {
        return { success: false, logs: simResult.value.logs, error: simResult.value.err };
    }

    // Send transaction to persist writes
    try {
        await sendAndConfirmTransaction(connection, transaction, [payer], {
            commitment: 'confirmed',
            skipPreflight: true,
        });
    } catch (e) { }

    return { success: true };
}

function test(name, condition, expected, actual, cu) {
    if (condition) {
        console.log(`  ${GREEN}✓${RESET} ${name} ${YELLOW}(${cu} CU)${RESET}`);
        testsPassed++;
    } else {
        console.log(`  ${RED}✗${RESET} ${name}`);
        console.log(`    Expected: ${expected}`);
        console.log(`    Actual:   "${actual}"`);
        testsFailed++;
    }
}

async function main() {
    console.log(`${CYAN}╔════════════════════════════════════════╗${RESET}`);
    console.log(`${CYAN}║   exec() and import sol_N Tests        ║${RESET}`);
    console.log(`${CYAN}╚════════════════════════════════════════╝${RESET}\n`);

    const connection = new Connection(RPC_URL, 'confirmed');
    const payer = loadPayer();
    const programId = loadProgramId(PIKA_KEYPAIR_PATH);

    console.log(`Program: ${programId.toString()}\n`);

    // Create test account for storing Python code
    console.log(`${CYAN}Creating test account...${RESET}`);
    const moduleAccount = await createTestAccount(connection, payer, programId, 256);
    console.log(`  Module account: ${moduleAccount.publicKey.toString()}\n`);

    // =========================================================================
    // exec() Tests - Execute inline code strings
    // =========================================================================
    console.log(`${CYAN}═══ exec() Builtin Tests ═══${RESET}`);

    // Test 1: exec() sets variable
    console.log(`\n${CYAN}Test 1: exec() sets variable${RESET}`);
    let result = await executePython(connection, programId, payer,
        `x=0\nexec("x=99")\nprint(x)`,
        [{ pubkey: moduleAccount.publicKey, writable: false }]);
    test('exec() sets variable in scope', result.output.includes('99'), '99', result.output, result.computeUnits);

    // Test 2: exec() defines function
    console.log(`\n${CYAN}Test 2: exec() defines function${RESET}`);
    result = await executePython(connection, programId, payer,
        `exec("def foo():\\n  return 7")\nprint(foo())`,
        [{ pubkey: moduleAccount.publicKey, writable: false }]);
    test('exec() defines callable function', result.output.includes('7'), '7', result.output, result.computeUnits);

    // Test 3: exec() with print statement
    console.log(`\n${CYAN}Test 3: exec() with print${RESET}`);
    result = await executePython(connection, programId, payer,
        `exec("print(100)")`,
        [{ pubkey: moduleAccount.publicKey, writable: false }]);
    test('exec() with print', result.output.includes('100'), '100', result.output, result.computeUnits);

    // Test 4: exec() with variable modification
    console.log(`\n${CYAN}Test 4: exec() modifies variable${RESET}`);
    result = await executePython(connection, programId, payer,
        `n=5\nexec("n=n*2")\nprint(n)`,
        [{ pubkey: moduleAccount.publicKey, writable: false }]);
    test('exec() modifies variable', result.output.includes('10'), '10', result.output, result.computeUnits);

    // Test 5: exec() with class
    console.log(`\n${CYAN}Test 5: exec() with class${RESET}`);
    result = await executePython(connection, programId, payer,
        `exec("class C:\\n  x=42")\nprint(C.x)`,
        [{ pubkey: moduleAccount.publicKey, writable: false }]);
    test('exec() defines class', result.output.includes('42'), '42', result.output, result.computeUnits);

    // =========================================================================
    // import sol_N Tests - Import from Solana accounts
    // =========================================================================
    console.log(`\n${CYAN}═══ import sol_N Tests ═══${RESET}`);

    // Test 6: Write module code to account
    console.log(`\n${CYAN}Test 6: Write module code to account${RESET}`);
    const moduleCode = 'VAL=42';
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nf.write("${moduleCode}")\nf.close()`,
        [{ pubkey: moduleAccount.publicKey, writable: true }]);
    test('Write module code', result.success, 'success', result.success ? 'success' : 'failed', result.computeUnits);

    // Test 7: import sol_0 accesses variable
    console.log(`\n${CYAN}Test 7: import sol_0 accesses variable${RESET}`);
    result = await executePython(connection, programId, payer,
        `import sol_0\nprint(sol_0.VAL)`,
        [{ pubkey: moduleAccount.publicKey, writable: false }]);
    test('import sol_0 accesses VAL', result.output.includes('42'), '42', result.output, result.computeUnits);

    // Test 8: import sol_0 with function
    console.log(`\n${CYAN}Test 8: import sol_0 with function${RESET}`);
    // Write function to account
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nf.write("def add(a,b):\\n  return a+b")\nf.close()`,
        [{ pubkey: moduleAccount.publicKey, writable: true }]);
    // Import and call
    result = await executePython(connection, programId, payer,
        `import sol_0\nprint(sol_0.add(3,4))`,
        [{ pubkey: moduleAccount.publicKey, writable: false }]);
    test('import sol_0 calls function', result.output.includes('7'), '7', result.output, result.computeUnits);

    // Test 9: import sol_0 with class
    console.log(`\n${CYAN}Test 9: import sol_0 with class${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nf.write("class Math:\\n  PI=314")\nf.close()`,
        [{ pubkey: moduleAccount.publicKey, writable: true }]);
    result = await executePython(connection, programId, payer,
        `import sol_0\nprint(sol_0.Math.PI)`,
        [{ pubkey: moduleAccount.publicKey, writable: false }]);
    test('import sol_0 accesses class attr', result.output.includes('314'), '314', result.output, result.computeUnits);

    // Test 10: import sol_0 multiple attributes
    console.log(`\n${CYAN}Test 10: import sol_0 multiple attributes${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nf.write("A=1\\nB=2\\nC=3")\nf.close()`,
        [{ pubkey: moduleAccount.publicKey, writable: true }]);
    result = await executePython(connection, programId, payer,
        `import sol_0\nprint(sol_0.A)`,
        [{ pubkey: moduleAccount.publicKey, writable: false }]);
    test('import sol_0 multiple attrs', result.output.includes('1'), '1', result.output, result.computeUnits);

    // =========================================================================
    // Bytecode import tests
    // =========================================================================
    console.log(`\n${CYAN}═══ Bytecode Import Tests ═══${RESET}`);

    // Test 11: Generate bytecode for module
    console.log(`\n${CYAN}Test 11: Generate bytecode for module${RESET}`);
    const bytecodeResult = await generateBytecode(connection, programId, payer, 'X=999');
    test('Generate bytecode', bytecodeResult.success && bytecodeResult.bytecode.length > 0,
        'bytecode generated', bytecodeResult.success ? `${bytecodeResult.bytecode.length} bytes` : 'failed',
        bytecodeResult.computeUnits);
    if (bytecodeResult.success) {
        console.log(`    Bytecode: ${bytecodeResult.bytecode.slice(0, 20).toString('hex')}...`);
        console.log(`    First byte: 0x${bytecodeResult.bytecode[0].toString(16).padStart(2, '0')} (should be 0x0f for pyoc header)`);
    }

    // Test 12: Write bytecode to account using MODE_WRITE_ACCOUNT (0x03)
    console.log(`\n${CYAN}Test 12: Write bytecode to account${RESET}`);
    if (bytecodeResult.success) {
        // Write bytecode directly to account using mode 0x03 (bypasses Python parser)
        const bytecodeAccount = await createTestAccount(connection, payer, programId, 256);
        console.log(`  Bytecode account: ${bytecodeAccount.publicKey.toString()}`);

        // Use mode 0x03 to write raw bytes directly to the account
        console.log(`  Writing ${bytecodeResult.bytecode.length} bytes of bytecode via MODE_WRITE_ACCOUNT`);
        const writeResult = await writeAccountDirect(connection, programId, payer, bytecodeAccount, bytecodeResult.bytecode);
        if (!writeResult.success) {
            console.log(`  Error: ${JSON.stringify(writeResult.error)}`);
            console.log(`  Logs: ${(writeResult.logs || []).join('\n        ')}`);
        }
        test('Write bytecode to account', writeResult.success, 'success', writeResult.success ? 'success' : 'failed', 0);

        // Test 13: Import bytecode module
        console.log(`\n${CYAN}Test 13: Import bytecode module${RESET}`);
        result = await executePython(connection, programId, payer,
            `import sol_0\nprint(sol_0.X)`,
            [{ pubkey: bytecodeAccount.publicKey, writable: false }]);
        test('import bytecode module accesses X', result.output.includes('999'), '999', result.output, result.computeUnits);
    } else {
        console.log(`  ${YELLOW}Skipping bytecode import tests - bytecode generation failed${RESET}`);
    }

    // =========================================================================
    // Summary
    // =========================================================================
    console.log(`\n${CYAN}╔════════════════════════════════════════╗${RESET}`);
    console.log(`${CYAN}║               Summary                  ║${RESET}`);
    console.log(`${CYAN}╚════════════════════════════════════════╝${RESET}`);
    console.log(`  ${GREEN}Passed: ${testsPassed}${RESET}`);
    if (testsFailed > 0) {
        console.log(`  ${RED}Failed: ${testsFailed}${RESET}`);
    }
    console.log();

    if (testsFailed > 0) {
        process.exit(1);
    }
}

main().catch(err => {
    console.error(`${RED}Error: ${err.message}${RESET}`);
    console.error(err.stack);
    process.exit(1);
});
