#!/usr/bin/env node
/**
 * Comprehensive VFS Tests
 *
 * Tests the virtual filesystem - each test does minimal operations
 * to stay within compute budget.
 */

const {
    Connection,
    Keypair,
    PublicKey,
    Transaction,
    TransactionInstruction,
    sendAndConfirmTransaction,
    ComputeBudgetProgram,
    SystemProgram,
} = require('@solana/web3.js');
const fs = require('fs');
const path = require('path');

const RPC_URL = 'http://localhost:8899';
const PIKA_KEYPAIR_PATH = path.join(__dirname, '..', 'pika-keypair.json');

const MODE_EXECUTE_SCRIPT = 0x00;

const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const CYAN = '\x1b[36m';
const RESET = '\x1b[0m';

let testsPassed = 0;
let testsFailed = 0;

function loadProgramId(keypairPath) {
    const keypairData = JSON.parse(fs.readFileSync(keypairPath, 'utf8'));
    const keypair = Keypair.fromSecretKey(new Uint8Array(keypairData));
    return keypair.publicKey;
}

function loadPayer() {
    const payerKeypairPath = process.env.HOME + '/.config/solana/id.json';
    const payerKeypair = JSON.parse(fs.readFileSync(payerKeypairPath, 'utf8'));
    return Keypair.fromSecretKey(new Uint8Array(payerKeypair));
}

async function createTestAccount(connection, payer, programId, dataSize) {
    const testAccount = Keypair.generate();
    const rentExempt = await connection.getMinimumBalanceForRentExemption(dataSize);

    const createTx = new Transaction().add(
        SystemProgram.createAccount({
            fromPubkey: payer.publicKey,
            newAccountPubkey: testAccount.publicKey,
            lamports: rentExempt,
            space: dataSize,
            programId: programId,
        })
    );

    await sendAndConfirmTransaction(connection, createTx, [payer, testAccount]);
    return testAccount;
}

async function executePython(connection, programId, payer, pythonCode, accounts) {
    const modeBuffer = Buffer.alloc(1);
    modeBuffer.writeUInt8(MODE_EXECUTE_SCRIPT, 0);
    const data = Buffer.concat([modeBuffer, Buffer.from(pythonCode, 'utf8')]);

    const keys = accounts.map(acc => ({
        pubkey: acc.pubkey,
        isSigner: false,
        isWritable: acc.writable,
    }));

    const instruction = new TransactionInstruction({
        keys,
        programId,
        data,
    });

    const transaction = new Transaction();
    transaction.add(
        ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
        ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        instruction
    );

    transaction.feePayer = payer.publicKey;
    transaction.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;

    const simResult = await connection.simulateTransaction(transaction);

    // Extract output from logs
    const output = simResult.value.logs?.filter(log =>
        log.startsWith('Program log:') &&
        !log.includes('Generated bytecode') &&
        !log.includes('VFS initialized')
    ).map(log => log.replace('Program log: ', '')).join('\n') || '';

    if (simResult.value.err) {
        if (process.env.DEBUG) {
            console.log(`  ${RED}Error:${RESET}`, simResult.value.err);
            console.log(`  Logs:`, simResult.value.logs?.slice(-5).join('\n  '));
        }
        return { success: false, output, logs: simResult.value.logs, error: simResult.value.err };
    }

    // Send transaction to persist writes
    try {
        await sendAndConfirmTransaction(connection, transaction, [payer], {
            commitment: 'confirmed',
            skipPreflight: true,
        });
    } catch (e) { }

    return { success: true, output, logs: simResult.value.logs };
}

function test(name, condition, expected, actual) {
    if (condition) {
        console.log(`  ${GREEN}✓${RESET} ${name}`);
        testsPassed++;
    } else {
        console.log(`  ${RED}✗${RESET} ${name}`);
        console.log(`    Expected: ${expected}`);
        console.log(`    Actual:   "${actual}"`);
        testsFailed++;
    }
}

async function main() {
    console.log(`${CYAN}╔════════════════════════════════════════╗${RESET}`);
    console.log(`${CYAN}║   PikaPython VFS Comprehensive Tests   ║${RESET}`);
    console.log(`${CYAN}╚════════════════════════════════════════╝${RESET}\n`);

    const connection = new Connection(RPC_URL, 'confirmed');
    const payer = loadPayer();
    const programId = loadProgramId(PIKA_KEYPAIR_PATH);

    console.log(`Program: ${programId.toString()}\n`);

    // Create test accounts
    console.log(`${CYAN}Creating test accounts...${RESET}`);
    const account1 = await createTestAccount(connection, payer, programId, 64);
    const account2 = await createTestAccount(connection, payer, programId, 128);
    const account3 = await createTestAccount(connection, payer, programId, 32);
    console.log(`  Account 0: ${account1.publicKey.toString()} (64 bytes)`);
    console.log(`  Account 1: ${account2.publicKey.toString()} (128 bytes)`);
    console.log(`  Account 2: ${account3.publicKey.toString()} (32 bytes)\n`);

    // =========================================================================
    // Test 1: Write to account
    // =========================================================================
    console.log(`${CYAN}Test 1: Write to account${RESET}`);
    let result = await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nn=f.write("ABCDEFGH")\nprint(n)\nf.close()`,
        [{ pubkey: account1.publicKey, writable: true }]);
    test('write() returns 8', result.output.includes('8'), '8', result.output);

    // =========================================================================
    // Test 2: Read from account
    // =========================================================================
    console.log(`\n${CYAN}Test 2: Read from account${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","r")\ndata=f.read(8)\nprint(data)\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false }]);
    test('read(8) returns "ABCDEFGH"', result.output.includes('ABCDEFGH'), 'ABCDEFGH', result.output);

    // =========================================================================
    // Test 3: tell() returns position
    // =========================================================================
    console.log(`\n${CYAN}Test 3: tell() returns position${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nf.write("12345")\nprint(f.tell())\nf.close()`,
        [{ pubkey: account1.publicKey, writable: true }]);
    test('tell() after write(5) returns 5', result.output.includes('5'), '5', result.output);

    // =========================================================================
    // Test 4: seek() then read
    // =========================================================================
    console.log(`\n${CYAN}Test 4: seek() then read${RESET}`);
    // First write known data
    await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nf.write("ABCDEFGHIJ")\nf.close()`,
        [{ pubkey: account1.publicKey, writable: true }]);

    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","r")\nf.seek(5)\nprint(f.read(5))\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false }]);
    test('seek(5) then read(5) returns "FGHIJ"', result.output.includes('FGHIJ'), 'FGHIJ', result.output);

    // =========================================================================
    // Test 5: Read partial
    // =========================================================================
    console.log(`\n${CYAN}Test 5: Read partial data${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","r")\nprint(f.read(3))\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false }]);
    test('read(3) returns "ABC"', result.output.includes('ABC'), 'ABC', result.output);

    // =========================================================================
    // Test 6: Write to second account
    // =========================================================================
    console.log(`\n${CYAN}Test 6: Write to second account${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/1","w")\nf.write("SECOND!")\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false },
         { pubkey: account2.publicKey, writable: true }]);
    test('Write to /sol/1 succeeds', result.success, 'success', result.success ? 'success' : 'failed');

    // =========================================================================
    // Test 7: Read from second account
    // =========================================================================
    console.log(`\n${CYAN}Test 7: Read from second account${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/1","r")\nprint(f.read(7))\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false },
         { pubkey: account2.publicKey, writable: false }]);
    test('Read from /sol/1 returns "SECOND!"', result.output.includes('SECOND!'), 'SECOND!', result.output);

    // =========================================================================
    // Test 8: Sequential reads advance position
    // =========================================================================
    console.log(`\n${CYAN}Test 8: Sequential reads advance position${RESET}`);
    // First write
    await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nf.write("AABBCC")\nf.close()`,
        [{ pubkey: account1.publicKey, writable: true }]);

    // Read twice, print second - should be "BB" not "AA"
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","r")\nf.read(2)\nprint(f.read(2))\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false }]);
    test('Second read(2) returns "BB" (position advanced)',
        result.output.includes('BB'), 'BB', result.output);

    // =========================================================================
    // Test 9: Write to read-only fails
    // =========================================================================
    console.log(`\n${CYAN}Test 9: Write to read-only account${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nif f:\n  print("opened")\nelse:\n  print("none")`,
        [{ pubkey: account1.publicKey, writable: false }]);  // NOT writable
    test('Opening read-only for write returns None or 0 writes',
        result.output.includes('none') || !result.success,
        'none or failure', result.output || 'failed');

    // =========================================================================
    // Test 10: seek(0) resets position
    // =========================================================================
    console.log(`\n${CYAN}Test 10: seek(0) resets position${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","r")\nf.read(4)\nf.seek(0)\nprint(f.tell())\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false }]);
    test('seek(0) resets position to 0', result.output.includes('0'), '0', result.output);

    // =========================================================================
    // Test 11: Write at offset with seek
    // =========================================================================
    console.log(`\n${CYAN}Test 11: Write at offset${RESET}`);
    // First fill with X
    await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nf.write("XXXXXXXX")\nf.close()`,
        [{ pubkey: account1.publicKey, writable: true }]);
    // Then write YY at position 3
    await executePython(connection, programId, payer,
        `f=open("/sol/0","w")\nf.seek(3)\nf.write("YY")\nf.close()`,
        [{ pubkey: account1.publicKey, writable: true }]);
    // Read back
    result = await executePython(connection, programId, payer,
        `f=open("/sol/0","r")\nprint(f.read(8))\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false }]);
    test('Write at offset produces "XXXYYXXX"',
        result.output.includes('XXXYYXXX'), 'XXXYYXXX', result.output);

    // =========================================================================
    // Test 12: Third account
    // =========================================================================
    console.log(`\n${CYAN}Test 12: Third account access${RESET}`);
    result = await executePython(connection, programId, payer,
        `f=open("/sol/2","w")\nf.write("THREE")\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false },
         { pubkey: account2.publicKey, writable: false },
         { pubkey: account3.publicKey, writable: true }]);
    test('Write to /sol/2 succeeds', result.success, 'success', result.success ? 'success' : 'failed');

    result = await executePython(connection, programId, payer,
        `f=open("/sol/2","r")\nprint(f.read(5))\nf.close()`,
        [{ pubkey: account1.publicKey, writable: false },
         { pubkey: account2.publicKey, writable: false },
         { pubkey: account3.publicKey, writable: false }]);
    test('Read from /sol/2 returns "THREE"', result.output.includes('THREE'), 'THREE', result.output);

    // =========================================================================
    // Summary
    // =========================================================================
    console.log(`\n${CYAN}╔════════════════════════════════════════╗${RESET}`);
    console.log(`${CYAN}║               Summary                  ║${RESET}`);
    console.log(`${CYAN}╚════════════════════════════════════════╝${RESET}`);
    console.log(`  ${GREEN}Passed: ${testsPassed}${RESET}`);
    if (testsFailed > 0) {
        console.log(`  ${RED}Failed: ${testsFailed}${RESET}`);
    }
    console.log();

    if (testsFailed > 0) {
        process.exit(1);
    }
}

main().catch(err => {
    console.error(`${RED}Error: ${err.message}${RESET}`);
    console.error(err.stack);
    process.exit(1);
});
