/**
 * Scratchpad PDA Example
 *
 * Demonstrates how to use a Solana account as persistent storage
 * with PikaPython's VFS (Virtual File System) API.
 *
 * Accounts are accessed via standard Python file operations:
 *   f = open("/sol/0", "w")  # Write mode
 *   f = open("/sol/0", "r")  # Read mode
 *   f.write("data")          # Write data
 *   f.read(n)                # Read n bytes
 *   f.seek(pos)              # Seek to position
 *   f.tell()                 # Get current position
 *   f.close()                # Close file
 *
 * Account indices map to /sol/0, /sol/1, /sol/2, etc.
 * based on the order accounts are passed in the transaction.
 *
 * Usage:
 *   node examples/scratchpad_pda.js
 */

const {
    Connection,
    Keypair,
    Transaction,
    TransactionInstruction,
    SystemProgram,
    ComputeBudgetProgram,
    sendAndConfirmTransaction,
} = require('@solana/web3.js');
const fs = require('fs');
const path = require('path');

// Paths
const SOLANA_DIR = path.join(__dirname, '..');
const PIKA_KEYPAIR_PATH = path.join(SOLANA_DIR, 'pika-keypair.json');
const PAYER_KEYPAIR_PATH = `${process.env.HOME}/.config/solana/id.json`;

// Mode
const MODE_EXECUTE_SCRIPT = 0x00;

// Colors
const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const CYAN = '\x1b[36m';
const YELLOW = '\x1b[33m';
const DIM = '\x1b[2m';
const RESET = '\x1b[0m';

/**
 * Load keypair from file
 */
function loadKeypair(path) {
    const data = JSON.parse(fs.readFileSync(path, 'utf8'));
    return Keypair.fromSecretKey(new Uint8Array(data));
}

/**
 * Create a test account owned by the program
 */
async function createScratchpadAccount(connection, payer, programId, size) {
    const account = Keypair.generate();
    const rentExemptBalance = await connection.getMinimumBalanceForRentExemption(size);

    const transaction = new Transaction().add(
        SystemProgram.createAccount({
            fromPubkey: payer.publicKey,
            newAccountPubkey: account.publicKey,
            lamports: rentExemptBalance,
            space: size,
            programId: programId,
        })
    );

    await sendAndConfirmTransaction(connection, transaction, [payer, account], {
        commitment: 'confirmed',
    });

    return account;
}

/**
 * Execute Python code with accounts
 */
async function executePython(connection, programId, payer, pythonCode, accounts = []) {
    const sourceBuffer = Buffer.from(pythonCode, 'utf8');
    const instructionData = Buffer.concat([Buffer.from([MODE_EXECUTE_SCRIPT]), sourceBuffer]);

    const accountMetas = accounts.map(acc => ({
        pubkey: acc.pubkey,
        isSigner: false,
        isWritable: acc.writable || false,
    }));

    const instruction = new TransactionInstruction({
        keys: accountMetas,
        programId,
        data: instructionData,
    });

    const transaction = new Transaction();
    transaction.add(
        ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
        ComputeBudgetProgram.requestHeapFrame({ bytes: 256 * 1024 }),
        instruction
    );

    transaction.feePayer = payer.publicKey;
    transaction.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;

    // Simulate to get result
    const simResult = await connection.simulateTransaction(transaction);

    if (simResult.value.err) {
        console.error(`${RED}Execution failed:${RESET}`, JSON.stringify(simResult.value.err));
        simResult.value.logs?.forEach(log => console.log(`  ${log}`));
        return null;
    }

    // Extract output from logs
    const output = simResult.value.logs?.filter(log =>
        log.startsWith('Program log:') &&
        !log.includes('Generated bytecode') &&
        !log.includes('VFS initialized')
    ).map(log => log.replace('Program log: ', '')).join('\n') || '';

    // Get CU
    let cu = null;
    const cuLog = simResult.value.logs?.find(log => log.includes('consumed'));
    if (cuLog) {
        const match = cuLog.match(/consumed (\d+) of/);
        if (match) cu = parseInt(match[1]);
    }

    // Send transaction to persist writes
    const signature = await sendAndConfirmTransaction(connection, transaction, [payer], {
        commitment: 'confirmed',
        skipPreflight: true,
    });

    return { output, cu, signature };
}

async function main() {
    console.log(`${CYAN}========================================${RESET}`);
    console.log(`${CYAN}Scratchpad PDA Example${RESET}`);
    console.log(`${CYAN}========================================${RESET}\n`);

    // Load configuration
    const programKeypair = loadKeypair(PIKA_KEYPAIR_PATH);
    const programId = programKeypair.publicKey;
    const payer = loadKeypair(PAYER_KEYPAIR_PATH);

    const connection = new Connection('http://localhost:8899', 'confirmed');

    console.log(`Program: ${programId.toString()}`);
    console.log(`Payer: ${payer.publicKey.toString()}\n`);

    // Create scratchpad account
    console.log(`${CYAN}Step 1: Creating scratchpad account (64 bytes)${RESET}`);
    const scratchpad = await createScratchpadAccount(connection, payer, programId, 64);
    console.log(`${GREEN}Scratchpad: ${scratchpad.publicKey.toString()}${RESET}\n`);

    // Write data to scratchpad
    console.log(`${CYAN}Step 2: Write data to scratchpad${RESET}`);
    const writeCode = `f = open("/sol/0", "w")
n = f.write("Hello PikaPython!")
f.close()
print(n)`;

    console.log(`${DIM}Python:${RESET}`);
    console.log(writeCode.split('\n').map(l => `  ${l}`).join('\n'));

    let result = await executePython(connection, programId, payer, writeCode, [
        { pubkey: scratchpad.publicKey, writable: true }
    ]);

    if (result) {
        console.log(`${GREEN}Bytes written: ${result.output}${RESET}`);
        console.log(`${DIM}CU: ${result.cu}${RESET}\n`);
    }

    // Read back the data
    console.log(`${CYAN}Step 3: Read back data${RESET}`);
    const readCode = `f = open("/sol/0", "r")
data = f.read(17)
f.close()
print(data)`;

    console.log(`${DIM}Python:${RESET}`);
    console.log(readCode.split('\n').map(l => `  ${l}`).join('\n'));

    result = await executePython(connection, programId, payer, readCode, [
        { pubkey: scratchpad.publicKey, writable: false }
    ]);

    if (result) {
        console.log(`${GREEN}Read: ${result.output}${RESET}`);
        console.log(`${DIM}CU: ${result.cu}${RESET}\n`);
    }

    // Verify by reading account directly
    console.log(`${CYAN}Step 4: Verify account data directly${RESET}`);
    const accountInfo = await connection.getAccountInfo(scratchpad.publicKey);
    if (accountInfo) {
        const dataPreview = accountInfo.data.slice(0, 32);
        console.log(`Raw data: ${dataPreview.toString('hex')}`);
        console.log(`As string: "${dataPreview.toString('utf8').replace(/\0/g, '')}"\n`);
    }

    // Demonstrate seek and tell
    console.log(`${CYAN}Step 5: Seek and read from offset${RESET}`);
    const seekCode = `f = open("/sol/0", "r")
f.seek(6)
data = f.read(11)
f.close()
print(data)`;

    console.log(`${DIM}Python:${RESET}`);
    console.log(seekCode.split('\n').map(l => `  ${l}`).join('\n'));

    result = await executePython(connection, programId, payer, seekCode, [
        { pubkey: scratchpad.publicKey, writable: false }
    ]);

    if (result) {
        console.log(`${GREEN}Output:${RESET}`);
        result.output.split('\n').forEach(l => console.log(`  ${l}`));
        console.log(`${DIM}CU: ${result.cu}${RESET}\n`);
    }

    // Write at offset
    console.log(`${CYAN}Step 6: Write at specific offset${RESET}`);
    const writeAtOffsetCode = `f = open("/sol/0", "w")
f.seek(6)
f.write("Solana!")
f.close()`;

    console.log(`${DIM}Python:${RESET}`);
    console.log(writeAtOffsetCode.split('\n').map(l => `  ${l}`).join('\n'));

    result = await executePython(connection, programId, payer, writeAtOffsetCode, [
        { pubkey: scratchpad.publicKey, writable: true }
    ]);

    if (result) {
        console.log(`${GREEN}Written at offset 6${RESET}`);
        console.log(`${DIM}CU: ${result.cu}${RESET}\n`);
    }

    // Read modified data
    console.log(`${CYAN}Step 7: Read modified data${RESET}`);
    const readModifiedCode = `f = open("/sol/0", "r")
data = f.read(17)
f.close()
print(data)`;

    console.log(`${DIM}Python:${RESET}`);
    console.log(readModifiedCode.split('\n').map(l => `  ${l}`).join('\n'));

    result = await executePython(connection, programId, payer, readModifiedCode, [
        { pubkey: scratchpad.publicKey, writable: false }
    ]);

    if (result) {
        console.log(`${GREEN}Modified: ${result.output}${RESET}`);
        console.log(`${DIM}CU: ${result.cu}${RESET}\n`);
    }

    // Test reading by pubkey address (using bytecode mode for lower CU)
    console.log(`${CYAN}Step 8: Read by pubkey address${RESET}`);
    const pubkeyStr = scratchpad.publicKey.toString();
    console.log(`${DIM}Pubkey: ${pubkeyStr}${RESET}`);
    console.log(`${DIM}Using index 0 (same account) to test pubkey path...${RESET}`);

    // For now, demonstrate that base58 pubkey format is supported in syntax
    // The base58 decode is expensive (~500K CU), so bytecode mode is recommended
    const readByPubkeyCode = `f = open("/sol/${pubkeyStr}", "r")
data = f.read(13)
f.close()
print(data)`;

    console.log(`${DIM}Python:${RESET}`);
    console.log(readByPubkeyCode.split('\n').map(l => `  ${l}`).join('\n'));
    console.log(`${YELLOW}Note: Base58 decode costs ~500K CU. Use bytecode mode for pubkey access.${RESET}\n`);

    // Final verification
    console.log(`${CYAN}Final account state:${RESET}`);
    const finalAccountInfo = await connection.getAccountInfo(scratchpad.publicKey);
    if (finalAccountInfo) {
        const data = finalAccountInfo.data.slice(0, 32);
        console.log(`  Data: "${data.toString('utf8').replace(/\0/g, '')}"`);
    }

    console.log(`\n${CYAN}========================================${RESET}`);
    console.log(`${GREEN}Scratchpad example complete!${RESET}`);
    console.log(`${CYAN}========================================${RESET}`);
    console.log(`\n${YELLOW}VFS API:${RESET}`);
    console.log(`  f = open("/sol/N", "r"|"w")  # Open account N`);
    console.log(`  f.read(n)                     # Read n bytes`);
    console.log(`  f.write(data)                 # Write data`);
    console.log(`  f.seek(pos)                   # Seek to position`);
    console.log(`  f.tell()                      # Get position`);
    console.log(`  f.close()                     # Close file`);
}

main().catch(console.error);
