/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include <stdio.h>
#include <stdlib.h>
#include "BaseObj.h"
#include "PikaMain.h"
#include "PikaStdLib_SysObj.h"
#include "_math.h"

#include "TinyObj.h"

#ifndef PIKA_MODULE_MAIN_DISABLE
class_def(PikaMain){
    __BEFORE_MOETHOD_DEF
};
class_inhert(PikaMain, PikaStdLib_SysObj);

PikaObj *New_PikaMain(Args *args){
    PikaObj *self = New_PikaStdLib_SysObj(args);
#ifndef PIKA_MODULE__MATH_DISABLE
    obj_newObj(self, "_math", "_math", New__math);
#endif
    obj_setClass(self, PikaMain);
    return self;
}

Arg *PikaMain(PikaObj *self){
    return obj_newObjInPackage(New_PikaMain);
}
#endif

#ifndef PIKA_MODULE__MATH_DISABLE
void _math___init__Method(PikaObj *self, Args *_args_){
    _math___init__(self);
}
method_typedef(
    _math___init__,
    "__init__", ""
);

void _math_acosMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_acos(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_acos,
    "acos", "x"
);

void _math_asinMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_asin(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_asin,
    "asin", "x"
);

void _math_atanMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_atan(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_atan,
    "atan", "x"
);

void _math_atan2Method(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float y = args_getFloat(_args_, "y");
    pika_float res = _math_atan2(self, x, y);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_atan2,
    "atan2", "x,y"
);

void _math_ceilMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    int res = _math_ceil(self, x);
    method_returnInt(_args_, res);
}
method_typedef(
    _math_ceil,
    "ceil", "x"
);

void _math_cosMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_cos(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_cos,
    "cos", "x"
);

void _math_coshMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_cosh(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_cosh,
    "cosh", "x"
);

void _math_degreesMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_degrees(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_degrees,
    "degrees", "x"
);

void _math_expMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_exp(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_exp,
    "exp", "x"
);

void _math_fabsMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_fabs(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_fabs,
    "fabs", "x"
);

void _math_floorMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    int res = _math_floor(self, x);
    method_returnInt(_args_, res);
}
method_typedef(
    _math_floor,
    "floor", "x"
);

void _math_fmodMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float y = args_getFloat(_args_, "y");
    pika_float res = _math_fmod(self, x, y);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_fmod,
    "fmod", "x,y"
);

void _math_logMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_log(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_log,
    "log", "x"
);

void _math_log10Method(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_log10(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_log10,
    "log10", "x"
);

void _math_log2Method(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_log2(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_log2,
    "log2", "x"
);

void _math_powMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float y = args_getFloat(_args_, "y");
    pika_float res = _math_pow(self, x, y);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_pow,
    "pow", "x,y"
);

void _math_radiansMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_radians(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_radians,
    "radians", "x"
);

void _math_remainderMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float y = args_getFloat(_args_, "y");
    pika_float res = _math_remainder(self, x, y);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_remainder,
    "remainder", "x,y"
);

void _math_sinMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_sin(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_sin,
    "sin", "x"
);

void _math_sinhMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_sinh(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_sinh,
    "sinh", "x"
);

void _math_sqrtMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_sqrt(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_sqrt,
    "sqrt", "x"
);

void _math_tanMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_tan(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_tan,
    "tan", "x"
);

void _math_tanhMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_tanh(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_tanh,
    "tanh", "x"
);

void _math_truncMethod(PikaObj *self, Args *_args_){
    pika_float x = args_getFloat(_args_, "x");
    pika_float res = _math_trunc(self, x);
    method_returnFloat(_args_, res);
}
method_typedef(
    _math_trunc,
    "trunc", "x"
);

class_def(_math){
    __BEFORE_MOETHOD_DEF
    method_def(_math_degrees, 144734852),
    method_def(_math_cos, 193488586),
    method_def(_math_exp, 193491058),
    method_def(_math_log, 193498375),
    method_def(_math_pow, 193502747),
    method_def(_math_sin, 193505807),
    method_def(_math_tan, 193506632),
    method_def(_math_atan2, 253464571),
    method_def(_math_floor, 259122023),
    method_def(_math_log10, 266334536),
    method_def(_math_trunc, 275947025),
    method_def(_math_radians, 884990407),
    method_def(_math___init__, 904762485),
    method_def(_math_remainder, 939143804),
    method_def(_math_acos, 2090071083),
    method_def(_math_asin, 2090088304),
    method_def(_math_atan, 2090089129),
    method_def(_math_ceil, 2090144930),
    method_def(_math_cosh, 2090156146),
    method_def(_math_fabs, 2090248161),
    method_def(_math_fmod, 2090261643),
    method_def(_math_log2, 2090479129),
    method_def(_math_sinh, 2090724439),
    method_def(_math_sqrt, 2090733295),
    method_def(_math_tanh, 2090751664),
};
class_inhert(_math, TinyObj);

PikaObj *New__math(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, _math);
    return self;
}
#endif

